name: PR-$(System.PullRequest.PullRequestNumber)-$(Date:yyyyMMdd)$(Rev:.rr)
trigger:
  # Batch merge builds together while a merge build is running
  batch: true
  branches:
    include:
    - master
    - ci
  paths:
    include:
    - '*'
    exclude:
    - /.github/*
pr:
  branches:
    include:
    - master
  paths:
    include:
    - '*'
    exclude:
    - /.github/*

variables:
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
  POWERSHELL_TELEMETRY_OPTOUT: 1
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1

resources:
- repo: self
  clean: true

jobs:
- template: templates/ci-build-test.yml
  parameters:
    pool: Hosted macOS
    jobName: macOS_build_test
    displayName: macOS Build/Test
